import { BlackCard, WhiteCard } from './types';

// Baralho base: "Cartas Contra Tugas" (adaptação portuguesa de Cards Against
// Humanity, CC BY-NC-SA), abrasileirado — texto em PT-BR natural e referências
// de Portugal trocadas por equivalentes brasileiras. O PDF original está em
// ref/. Para editar o jogo, basta mexer nestas listas: nas pretas, cada "____"
// é uma lacuna (pick = número de lacunas).

const BLACK_TEXTS: string[] = [
  'A melhor maneira de fazer sexo é ____.',
  'Eu nem sempre bebo cerveja, mas quando bebo é porque ____.',
  'Vou no Domingão entregar duas cestas de ____ pro Luciano Huck.',
  'Enquanto mijo, gosto de ficar vendo ____.',
  'O Jorge Jesus abandonou o Flamengo porque ____.',
  'O que eu fazia pelo Gabigol? ____!',
  'Se eu pudesse, comia ____ em todas as refeições.',
  '____? Foi isso que a sua mãe me disse ontem.',
  'O prato de hoje do cardápio vegetariano é ____.',
  'Eu fui preso no Natal porque ____.',
  '____ é definitivamente um 10/10.',
  'Escola é pra ____.',
  'Se tem algo estranho no seu bairro, quem você vai chamar? ____.',
  'Um dia vou ser o primeiro a criar ____.',
  'Minha escola precisava muito de um clube de ____.',
  'A coisa que eu mais odeio neste planeta é ____.',
  'Não há lugar como ____.',
  'Vamos construir ____, e a Argentina vai pagar.',
  'Passei metade da faculdade só ____.',
  'Adivinha só?! Achei ____.',
  'Você acha que os romanos tinham um deus pra ____?',
  'Segundo a última edição da revista Ana Maria, o que os homens mais desejam? ____.',
  '____ queima 500 calorias em uma hora.',
  'O novo best-seller: ____. Autor: ____.',
  'Na faculdade eu quero me formar em ____.',
  'Coisas que não deviam existir: ____, ____ e ____.',
  'Odeio admitir, mas já fiquei de pau duro por causa de ____.',
  'O Governo Brasileiro investiu milhões de reais pesquisando ____.',
  'Monta uma frase: ____ ____ ____.',
  'Não acredito que ____ aconteceu comigo DE NOVO.',
  'O melhor lugar pra passar o dia? ____. Sem dúvida.',
  'Todo bom livro policial precisa ter ____.',
  'Não acredito que o meu próprio país tem orgulho de ____.',
  'Pelo visto, ____ era completamente normal nos anos 60.',
  'www.____.com.br',
  'A nova novela das nove: ____.',
  'O maior desastre natural deste ano envolveu ____.',
  'Ah não! Acho que peguei ____.',
  'Eu, pessoalmente, acho que ____ vai contra a moral humana.',
  'Se eu virar presidente, vou legalizar ____.',
  'Minha nova paixão é ____.',
  '____ agora é liberado no Brasil.',
  'Só os brasileiros têm ____.',
  'Não é fazendo ____ que você vai conquistar o coração dela.',
  'Taxistas do país inteiro estão protestando contra ____.',
  'Um dia ainda abro um parque temático de ____.',
  'Fui demitido do meu último emprego porque ____.',
  'Estou de saco cheio de ____.',
  'Meu instrumento de tortura favorito é ____.',
  '____. Não tente isso em casa.',
  'Sopa do dia: sopa de ____.',
  'Todo mundo sempre esquece de ____.',
  'A polícia registrou vários homicídios, todos cometidos por ____.',
  'Consegui irritar um policial denunciando ____.',
  'O que diretor de pornô usa pra bater punheta? ____.',
  'A culpa de tudo é de ____.',
  'Eu preciso mesmo parar de pensar em ____.',
  'Resolução de Ano Novo: menos ____, mais ____.',
  'O que o gaúcho come no café da manhã? ____.',
  'Quem é que tá batendo na porta? ____.',
  'AVISO: ____ agora é proibido no ambiente de trabalho.',
  'Todo mundo odeia ____.',
  '____ contra ____: a nova série original da Record.',
  'Meu amigo é viciado em ____! Socorro!',
  'Eu dei meu coração pra ele, e ele me deu ____.',
  'Dediquei a maior parte da minha vida a ____. Que desperdício.',
  'A única coisa que o sexo oposto faz bem? ____.',
  'Um homem pegou 30 anos de cadeia por ____.',
  '____ é a principal causa de depressão.',
  'Pizza só é boa com uma pitada de ____.',
  'Comecei a me sentir velho quando entrei pra ____.',
  'Nunca imaginei que ____ pudesse ser tão gratificante.',
  '____ é superestimado.',
  'Em pelo menos 3 países, ____ é ilegal.',
  'Nunca pensei que veria ____ na convenção de ____.',
  "Quando vou ao McDonald's, sempre peço ____.",
  '____. É assim que o mundo vai acabar.',
  'Acharam um poema inédito do Drummond chamado ____.',
  'Fui banido da Havan por ____.',
  '____ parece que dói.',
  'Vou comprar ____.',
  'Pedi 10g de ____ pro meu traficante, e o desgraçado me entregou 10g de ____!',
  'No seu próximo filme, a Fernanda Montenegro é ____.',
  'Adolescentes do país inteiro não conseguem parar de ____.',
  'Pra dar uma apimentada na vida, comecei a fazer ____.',
  '____. Um sinal de que o mundo está acabando.',
  'Te fazia um ____ de você chorar e pedir mais.',
  'Você sabe se o(a) ____ vem?',
];

const WHITE_TEXTS: string[] = [
  'D. Pedro I gritando "independência ou morte" porque era um adolescente problemático.',
  'DEUS VULT!',
  'O Cabo da Boa Esperança.',
  'A descoberta do Brasil.',
  'O Zé Gotinha.',
  'A milícia do Rio de Janeiro.',
  'O lixão de Gramacho.',
  'Destruir os sonhos de um vencedor do The Voice.',
  'Uma alface da horta da sua avó.',
  'Um pau caindo de podre.',
  'Os vizinhos transando no meio da madrugada.',
  'Perder a virgindade com um galo.',
  'Sua mãe de quatro.',
  'Suor embaixo dos peitos.',
  'Sanduíche de esmegma.',
  'O Hino Nacional interpretado pela Gretchen.',
  'Um galão de 50 litros de lubrificante.',
  'Um PM comendo iogurte.',
  'A CBF.',
  'Qualquer porra aleatória.',
  'Sexo tântrico.',
  'Um pau cheio de varizes.',
  'Eutanasiar idosos gripados.',
  'O corpo quente do Tancredo Neves.',
  'O fogão da Ana Maria Braga.',
  'A garagem da vizinha.',
  'Brincar de pega-pega e não chamar o gordinho da turma B.',
  'Devolver o Acre pra Bolívia.',
  'Alucinações vívidas.',
  'Esconder a herpes atrás dos pelos pubianos.',
  'Uma câmara de gás.',
  'Palestra de coach motivacional.',
  'Chuva ácida derretendo a pele até o osso.',
  'Um corpo mutilado.',
  'Uma coreografia terrível.',
  'Ter um caso com a psicóloga.',
  'Chantagem.',
  'Morrer de câncer de pulmão.',
  'A ciência das ereções.',
  'O Comitê Olímpico.',
  'A comunidade muçulmana.',
  'Ter um tumor cerebral do tamanho de uma melancia.',
  'Usar Auschwitz como bode expiatório.',
  'Democracia.',
  'Monarquia.',
  'Uma centopeia humana.',
  'Violência doméstica.',
  'Fumar uma pedra de crack.',
  'Ajudar pessoas.',
  'Uma privada que fala.',
  'Transar de luz apagada e descobrir de manhã que era o cachorro.',
  'Virar pai porque ela esqueceu a pílula do dia seguinte.',
  'A churrascaria do Hitler.',
  'Fazer clones de mim mesmo pra usar como álibi.',
  'Ser enterrado vivo.',
  'O presidente da república.',
  'Reparar na porra seca na barba do cara.',
  'Zumbis.',
  'Uma privada sem fundo.',
  'Um pedido formal de desculpas.',
  'Animais gays.',
  'Negar tudo mesmo com o vídeo circulando.',
  'Conhecer alguém num show.',
  'Aquele amigo especial.',
  'Fingir intolerância a glúten.',
  'Usar a irmã como camisinha.',
  'Chineses.',
  'Pansexuais.',
  'Bissexuais.',
  'Falar putaria em Libras.',
  'Um africano albino.',
  'O que os homens fazem pra passar o tempo na cadeia.',
  'Esquecer de ser bonzinho.',
  'Cuecas mágicas.',
  'Estudar pra uma prova que não vai servir pra nada.',
  'Escorregar e enfiar sem querer.',
  'Adolescente no cio gozando pra todo lado.',
  'Estudar.',
  'Escrever uma canção de amor.',
  'Um português.',
  'Um argentino.',
  'Chegar à conclusão de que você é um merda.',
  'Reaproveitar camisinha usada.',
  'Uma corrida mortal de cadeiras de rodas.',
  'Síndrome de Down.',
  'Uma partida bem curta de roleta-russa.',
  'Um feiticeiro.',
  'Acabar o beck e fumar palha mesmo.',
  'Parkour.',
  'Química.',
  'Descobrir da pior maneira que você tem alergia a látex.',
  'Internet da Oi.',
  'O comércio de escravos.',
  'Alergia a água.',
  'Um photoshop óbvio.',
  'Produção de corpos em massa pra lucrar.',
  'Os bons e velhos tempos.',
  'Ganhar alguma coisa na vida.',
  'Fazer boquete num morto.',
  'O glorioso império brasileiro.',
  'O filho gay de um deputado da bancada da bíblia.',
  'Fascismo.',
  'Zoofilia.',
  'Envenenar a família inteira.',
  'Ser preso por atirar sem querer na namorada através da porta do banheiro.',
  'Morrer por dentro.',
  'Um coma.',
  'Mandar nude pra pessoa errada.',
  'Uma mesa de snacks saudáveis.',
  'Um bebê feio.',
  'Um anão fazendo striptease.',
  'Um tatuador cego.',
  'Uma posição do Kama Sutra.',
  'Ficar sem internet.',
  'Navegar em aba anônima.',
  'Espermicida.',
  'Gays homofóbicos.',
  'Flashbacks da Guerra do Paraguai.',
  'Um tamagotchi.',
  'Os filhos da ditadura.',
  'Começar uma revolução.',
  'Dizer adeus.',
  'Cena de pornô lésbico em que as duas minas já foram homens.',
  'Crianças autistas.',
  'Lampião.',
  'Fingir orgasmo por educação.',
  'Estar compensando alguma coisa.',
  'Uma sala cheia das minhas ex-namoradas.',
  'Injeção letal.',
  'Achar uma minhoca na maçã.',
  'Querer o melhor pra todo mundo.',
  'Incesto acidental.',
  'Cagar dentro de uma vagina.',
  'Uma viagem de barco gratuita pro inferno.',
  'Um monge pelado.',
  'Mijar no banho.',
  'Sodomia forçada.',
  'Mamilos gigantes.',
  'Jogar água nos moradores de rua.',
  'Aprender um idioma novo.',
  'Hálito de prostituta.',
  'Envenenar a ex-mulher.',
  'O lado bom da vida.',
  'Ser inocente demais pra esse jogo.',
  'A crise dos refugiados.',
  'Tensão sexual no almoço de família.',
  'Tomar banho no sangue de recém-nascidos.',
  'Exorcismo.',
  'Boas intenções.',
  'Asiáticos chorando porque vão comer o próprio cachorro no almoço.',
  'Uma mulher muçulmana apanhando do marido por ter mostrado tornozelo demais.',
  'Física.',
  'Um padre católico.',
  'Trabalho infantil.',
  'Bares gays.',
  'O início do fim.',
  'Aqueles pedacinhos de papel higiênico que ficam presos na bunda.',
  'Transformar virgens em não-virgens mesmo depois de elas dizerem não.',
  'Cometer suicídio.',
  'Biologia.',
  'Eclipse lunar.',
  'Usar um anão como bola.',
  'Raça ariana.',
  'Peidar no elevador cheio.',
  'Comprar brinquedos sexuais novos.',
  'Virgindade anal.',
  'Rir demais da própria piada.',
  'Jogar xadrez.',
  'Casar só pra transar.',
  'Esconder câmeras no quarto do meu crush.',
  'Ler contos eróticos em braille.',
  'Finalmente chegar à Europa depois de dias de viagem desde a Síria.',
  'Cheirar gás de cozinha no banho.',
  'Ter a atitude errada.',
  'Transar no elevador porque ele travou faz tempo.',
  'Uma escova de dentes com pelos pubianos.',
  'Falar sozinho.',
  'Uma fábrica de corpos.',
  'Tomar tanto Viagra que o pau explode.',
  'Errar o próprio suicídio.',
  'Esperma suicida.',
  'Colher e comer os órgãos de moradores de rua.',
  'O pau da sua mãe no meu cu.',
  'Descobrir tarde demais que você tem alergia a porra.',
  'Roubar pombos.',
  'Beijar a gêmea da namorada sem perceber.',
  'Se masturbar vendo fotos do Getúlio Vargas.',
  'Se masturbar vendo fotos de Brasília.',
  'Mandar nudes pra vó sem querer.',
  'O som de crianças gritando.',
  'Descobrir que sou o pior homem-bomba da história.',
  'Bigode de taxista.',
  'Prolapso anal.',
  'Invadir a Guiana Francesa.',
  'O grupo da família no WhatsApp.',
  'Ser ateu graças a Deus.',
  'A virgindade de um rapaz.',
  'Encher linguiça.',
  'Ter o mamilo esquerdo maior que os outros dois.',
  'Um polvo que adivinha resultado de jogo de futebol.',
  'Pênalti pro Flamengo!',
  'Uma prostituta virgem.',
  'Uma freira grávida.',
  'Uma macumba.',
  'Dirigir um caminhão em direção a uma feirinha de Natal.',
  'Um plano pra destruir a Terra.',
  'Stalkear o crush no Instagram.',
  'Uma garrafa pet de mijo quente.',
  'Gente alta.',
  'Um cadáver mais sexy que a sua esposa.',
  'Culpar os idosos.',
  'Prostitutas da OLX.',
  'Castrar anões.',
];

function countBlanks(text: string): number {
  return (text.match(/____/g) ?? []).length;
}

export const ALL_BLACK: BlackCard[] = BLACK_TEXTS.map((text, i) => ({
  id: `b${i}`,
  text,
  pick: Math.max(1, countBlanks(text)),
}));

export const ALL_WHITE: WhiteCard[] = WHITE_TEXTS.map((text, i) => ({
  id: `w${i}`,
  text,
}));
