import { BlackCard, WhiteCard } from './types';

// Baralho base: "Cartas Contra Tugas" (adaptação portuguesa de Cards Against
// Humanity, CC BY-NC-SA), traduzido para PT-BR — referências tugas mantidas.
// O PDF original está em ref/. Para editar o jogo, basta mexer nestas listas:
// nas pretas, cada "____" é uma lacuna (pick = número de lacunas).

const BLACK_TEXTS: string[] = [
  'A melhor maneira de fazer sexo é ____.',
  'Eu nem sempre bebo cerveja, mas quando bebo é porque ____.',
  'Vou ao Preço Certo levar duas cestas de ____ pro Fernando Mendes.',
  'Enquanto mijo, gosto de ver ____.',
  'O Jorge Jesus trocou o Benfica pelo Sporting porque ____.',
  'O que eu fazia pelo Éder? ____!',
  'Se eu pudesse, comia ____ em todas as refeições.',
  '____? Foi isso que a sua mãe me disse ontem.',
  'O prato de hoje do cardápio vegetariano é ____.',
  'Eu fui preso no Natal porque ____.',
  '____ é definitivamente um 10/10.',
  'Escola é coisa de ____.',
  'Se tem algo estranho no seu bairro, quem você vai chamar? ____.',
  'Um dia vou ser o primeiro a criar ____.',
  'Minha escola precisa mesmo de um clube de ____.',
  'Minha coisa menos favorita neste planeta é ____.',
  'Não há lugar como ____.',
  'Vamos fazer ____, e a Espanha vai pagar.',
  'Passei muitos dias da faculdade só ____.',
  'Adivinha!?!? Encontrei ____.',
  'Você acha que os romanos tinham um deus pra ____?',
  'Segundo a última edição da revista Maria, qual é a coisa que os homens mais desejam? ____.',
  '____ queima 500 calorias em uma hora.',
  'O novo best-seller: ____. Autor: ____.',
  'Na faculdade quero estudar ____.',
  'Coisas que não deviam existir: ____, ____ e ____.',
  'Odeio admitir, mas já tive uma ereção por causa de ____.',
  'O Governo Português investiu milhões de euros pesquisando ____.',
  'Faça uma frase: ____ ____ ____.',
  'Não acredito que ____ aconteceu comigo de novo.',
  'O melhor lugar pra passar o dia? ____. Sem dúvida.',
  'Todo bom livro policial precisa ter ____.',
  'Não acredito que o meu próprio país tem orgulho de ____.',
  'Parece que ____ era uma coisa comum de se fazer nos anos 60.',
  'www.____.pt',
  'O novo musical do Filipe La Féria: ____.',
  'O maior desastre natural deste ano envolveu ____.',
  'Ah não! Acho que peguei ____.',
  'Eu pessoalmente acredito que ____ é contra o código moral humano.',
  'Se eu virar primeiro-ministro, vou legalizar ____.',
  'Minha nova paixão é ____.',
  '____ agora é legal em Portugal.',
  'Só os portugueses têm ____.',
  'Você não vai conquistar o coração dela só fazendo ____.',
  'Taxistas do país inteiro estão protestando contra ____.',
  'Um dia quero criar um parque temático baseado em ____.',
  'Fui demitido do meu último emprego porque ____.',
  'Estou de saco cheio de ____.',
  'Meu instrumento de tortura favorito é ____.',
  '____. Não tente isso em casa.',
  'Sopa do dia: sopa de ____.',
  'Todo mundo se esquece de ____.',
  'Vários homicídios foram registrados, todos cometidos por ____.',
  'Irritei um policial ao denunciar ____.',
  'O que os diretores de pornô usam pra se masturbar? ____.',
  'A gente devia culpar ____ por tudo.',
  'Eu devia mesmo parar de pensar em ____.',
  'Resolução de Ano Novo: menos ____, mais ____.',
  'O que os nortenhos comem no café da manhã? ____.',
  'Quem está batendo na porta? ____.',
  'AVISO: ____ agora é proibido no local de trabalho.',
  'Todo mundo odeia ____.',
  '____ contra ____: o novo drama original produzido pela TVI.',
  'Meu amigo é viciado em ____! Socorro!',
  'Eu dei a ele o meu coração, e ele me deu ____.',
  'Dediquei a maior parte da minha vida a ____. Que perda de tempo!',
  'Em que o sexo oposto é bom? ____.',
  'Um homem foi condenado à prisão perpétua depois de ser acusado de ____.',
  '____ é geralmente a principal causa de depressão.',
  'Uma pizza só é boa se for finalizada com uma pitada de ____.',
  'Comecei a me sentir velho depois de entrar pra ____.',
  'Nunca imaginei que ____ pudesse ser tão gratificante.',
  '____ é superestimado.',
  'Em pelo menos 3 países, ____ é ilegal.',
  'Nunca pensei que veria ____ na convenção de ____.',
  "Quando vou ao McDonald's, sempre peço ____.",
  '____. É assim que o mundo vai acabar.',
  'Encontraram um poema inédito de Fernando Pessoa com o título ____.',
  'Fui banido do Minipreço por ____.',
  '____ parece doloroso.',
  'Vou comprar ____.',
  'Pedi 10g de ____ pro meu traficante, mas em vez disso ele me deu 10g de ____!',
  'No seu próximo filme, Joaquim de Almeida é ____.',
  'Adolescentes do país inteiro não conseguem parar de ____.',
  'Pra tornar minha vida mais interessante, comecei a fazer ____.',
  '____. Um sinal de que o mundo está acabando.',
  'Eu te fazia um ____ de morrer e chorar por mais!',
  'Você sabe se o(a) ____ vem?',
];

const WHITE_TEXTS: string[] = [
  'D. Afonso Henriques atacou a própria mãe porque era um adolescente problemático.',
  'DEUS VULT!',
  'O Cabo da Boa Esperança.',
  'A descoberta do Brasil.',
  'O Zé Povinho.',
  'A máfia da Amadora.',
  'A mata de Sintra.',
  'Destruir os sonhos de um vencedor do The Voice.',
  'Uma alface da horta da sua avó.',
  'Um pênis caindo de podre.',
  'Os vizinhos fazendo sexo no meio da noite.',
  'Ter a primeira experiência sexual com um galo.',
  'Sua mãe de quatro.',
  'Suor embaixo dos peitos.',
  'Sanduíche de esmegma.',
  'O Hino Nacional Português interpretado pelo Quim Barreiros.',
  'Um contêiner com 50 litros de lubrificante.',
  'Um policial comendo iogurte.',
  'A Gestifute.',
  'Uma caralhada qualquer.',
  'Sexo tântrico.',
  'Um pau cheio de varizes.',
  'Eutanasiar idosos gripados.',
  'O corpo quente de Mário Soares.',
  'O fogão da Sónia Brazão.',
  'A garagem da vizinha.',
  'Brincar de pega-pega e não chamar o gordinho da turma B.',
  'Iniciar a reconquista de Angola.',
  'Alucinações vívidas.',
  'Esconder minha herpes com pelos pubianos gigantes.',
  'Uma câmara de gás.',
  'Ouvir discursos motivacionais.',
  'Chuva ácida derretendo a pele até o osso.',
  'Um corpo mutilado.',
  'Uma coreografia terrível.',
  'Ter um caso com a psicóloga.',
  'Chantagear.',
  'Morrer de câncer de pulmão.',
  'A ciência das ereções.',
  'O Comitê Olímpico.',
  'A comunidade muçulmana.',
  'Ter um tumor cerebral do tamanho de uma melancia.',
  'Usar Auschwitz como bode expiatório.',
  'Democracia.',
  'Monarquia.',
  'Uma centopeia humana.',
  'Violência doméstica.',
  'Injetar heroína.',
  'Ajudar pessoas.',
  'Uma privada que fala.',
  'Fazer sexo com a esposa de luz apagada e descobrir depois que era o seu cachorro.',
  'Virar pai porque ela esqueceu a pílula do dia seguinte.',
  'A churrascaria do Hitler.',
  'Fazer clones de mim mesmo pra usar como álibi.',
  'Ser enterrado vivo.',
  'O presidente da república.',
  'Olhar pra barba de um homem e perceber que tem esperma nela.',
  'Zumbis.',
  'Uma privada sem fundo.',
  'Um pedido formal de desculpas.',
  'Animais gays.',
  'Negar mesmo com provas em vídeo.',
  'Conhecer alguém num show.',
  'Aquele amigo especial.',
  'Dizer que tem alergia a glúten.',
  'Usar a irmã como camisinha.',
  'Chineses.',
  'Pansexuais.',
  'Bissexuais.',
  'Falar putaria em língua de sinais.',
  'Um africano albino.',
  'O que os homens fazem pra passar o tempo na prisão.',
  'Esquecer de ser bonzinho.',
  'Cuecas mágicas.',
  'Estudar pra uma prova que você considera inútil.',
  'Escorregar e penetrá-la sem querer.',
  'Adolescentes de tesão ejaculando pra todo lado.',
  'Estudar.',
  'Escrever uma canção de amor.',
  'Um brasileiro.',
  'Um angolano.',
  'Chegar à conclusão de que você é um merda.',
  'Ter que reutilizar uma camisinha.',
  'Uma corrida mortal de cadeiras de rodas.',
  'Síndrome de Down.',
  'Um jogo bem curto de roleta-russa.',
  'Um feiticeiro.',
  'Ficar sem maconha e fumar palha como substituto.',
  'Parkour.',
  'Química.',
  'Descobrir da pior maneira que você tem alergia a látex.',
  'Wi-fi ruim.',
  'O comércio de escravos.',
  'Alergia a água.',
  'Um photoshop óbvio.',
  'Produção de corpos em massa pra lucrar.',
  'Os bons e velhos tempos.',
  'Ganhar alguma coisa na vida.',
  'Fazer boquete num morto.',
  'O glorioso império português.',
  'O filho gay de um militante do PNR.',
  'Fascismo.',
  'Zoofilia.',
  'Envenenar todos os membros da família.',
  'Ser preso por atirar sem querer na namorada através da porta do banheiro.',
  'Morrer por dentro.',
  'Um coma.',
  'Mandar nude pra pessoa errada.',
  'Uma seleção de lanchinhos saudáveis.',
  'Um bebê feio.',
  'Um anão fazendo striptease.',
  'Um tatuador cego.',
  'Uma posição do Kama Sutra.',
  'Ficar sem wi-fi.',
  'Usar o modo anônimo pra navegar na internet.',
  'Espermicida.',
  'Gays homofóbicos.',
  'Flashbacks da guerra colonial.',
  'Um tamagotchi.',
  'Os filhos da revolução.',
  'Começar uma revolução.',
  'Dizer adeus.',
  'Cena de pornô lésbico em que as duas garotas já foram homens.',
  'Crianças autistas.',
  'Viriato.',
  'Fingir orgasmo pra ser simpático.',
  'Compensar alguma coisa.',
  'Uma sala cheia das minhas ex-namoradas.',
  'Injeção letal.',
  'Encontrar uma minhoca na sua maçã.',
  'Querer o melhor pra todo mundo.',
  'Incesto acidental.',
  'Fazer cocô numa vagina.',
  'Uma viagem de barco gratuita pro inferno.',
  'Um monge pelado.',
  'Mijar durante o banho.',
  'Sodomia forçada.',
  'Mamilos gigantes.',
  'Jogar água nos moradores de rua.',
  'Aprender um idioma novo.',
  'Hálito de prostituta.',
  'Envenenar a ex-mulher.',
  'O lado bom da vida.',
  'Ser inocente demais pra esse jogo.',
  'A crise dos refugiados.',
  'Tensão sexual na reunião de família.',
  'Tomar banho no sangue de recém-nascidos.',
  'Exorcismo.',
  'Boas intenções.',
  'Asiáticos chorando porque vão comer o próprio cachorro no almoço.',
  'Uma mulher muçulmana apanhando do marido por ter mostrado tornozelo demais.',
  'Física.',
  'Um padre católico.',
  'Trabalho infantil.',
  'Bares gays.',
  'O início do fim.',
  'Aqueles pedacinhos de papel higiênico que ficam presos na bunda.',
  'Transformar virgens em não-virgens mesmo depois de elas dizerem não.',
  'Cometer suicídio.',
  'Biologia.',
  'Eclipse lunar.',
  'Usar um anão como bola.',
  'Raça ariana.',
  'Peidar dentro do elevador.',
  'Comprar brinquedos sexuais novos.',
  'Virgindade anal.',
  'Rir demais da própria piada.',
  'Jogar xadrez.',
  'Casar só pra poder fazer sexo.',
  'Esconder câmeras no quarto do meu crush.',
  'Ler contos eróticos em braille.',
  'Finalmente chegar à Europa depois de dias de viagem desde a Síria.',
  'Cheirar gás durante o banho.',
  'Ter a atitude errada.',
  'Fazer sexo no elevador porque ele está preso há tempo demais.',
  'Uma escova de dentes com pelos pubianos.',
  'Falar sozinho.',
  'Uma fábrica de corpos.',
  'Tomar tanto Viagra que o pau explode.',
  'Falhar num suicídio.',
  'Esperma suicida.',
  'Colher e comer os órgãos de moradores de rua.',
  'O pau da sua mãe no meu cu.',
  'Descobrir tarde demais que você tem alergia a sêmen.',
  'Roubar pombos.',
  'Ficar com a irmã gêmea da namorada sem saber.',
  'Se masturbar vendo fotos do Salazar.',
  'Se masturbar vendo fotos de Angola.',
  'Mandar sem querer uma mensagem sexy pra vó.',
  'O som de crianças gritando.',
  'Chegar à conclusão de que sou o pior homem-bomba de todos os tempos.',
  'Bigode de taxista.',
  'Prolapso anal.',
  'Iniciar a reconquista de Olivença.',
  'Reddit.',
  'Ser ateu graças a Deus.',
  'A virgindade de um rapaz.',
  'Encher tremoços.',
  'Ter o mamilo esquerdo maior que os outros dois.',
  'Um polvo que adivinha resultado de jogo de futebol.',
  'Pênalti pro Porto!',
  'Uma prostituta virgem.',
  'Uma freira grávida.',
  'Uma macumba.',
  'Dirigir um caminhão em direção a uma feirinha de Natal.',
  'Um plano pra destruir a Terra.',
  'Stalkear uma garota no Facebook.',
  'Uma garrafa de urina fresca.',
  'Gente alta.',
  'Um cadáver mais sexy que a sua esposa.',
  'Culpar os idosos.',
  'Prostitutas da OLX.',
  'Castrar anões.',
];

function countBlanks(text: string): number {
  return (text.match(/____/g) ?? []).length;
}

export const ALL_BLACK: BlackCard[] = BLACK_TEXTS.map((text, i) => ({
  id: `b${i}`,
  text,
  pick: Math.max(1, countBlanks(text)),
}));

export const ALL_WHITE: WhiteCard[] = WHITE_TEXTS.map((text, i) => ({
  id: `w${i}`,
  text,
}));
